[language-server.gpt]
command = "helix-gpt-deno"
args = ["--logFile", "/tmp/hx-gpt.log", "--handler", "copilot", "--copilotApiKey", "<api_key>"]

[[language]]
name = "python"
roots = ["pyproject.toml"]
auto-format = true
language-servers = ["pylsp", "gpt"]

[language-server.pylsp.config]
plugins.black.enabled = false
plugins.mypy.enabled = true
plugins.autopep8.enabled = false
plugins.yapf.enabled = false
plugins.pyflakes.enabled = false
plugins.pycodestyle.enabled = false
plugins.mccabe.enabled = false
plugins.ruff.enabled = true
plugins.ruff.formatEnabled = false
pylsp.plugins.rope_rename.enabled = false
pylsp.plugins.jedi_rename.enabled = false
plugins.pylsp_rope.rename = true
plugins.rope_autoimport.enabled = true

[language.formatter]
command = "ruff"
args = ["format", "-"]

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "\t" }
language-servers = [ "typescript-language-server", "gpt"]

[[language]]
name = "go"
language-servers = [ "gopls", "gpt"]

[language-server.gopls.config]
gofumpt = true
